
name: Docker
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Build Docker Image
      run: docker build -t swim-bot-rs:{{ version }} .

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Set in the repo's secrets
        password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Set in the repo's secrets

    - name: Push Image to DockerHub
      run: docker push swim-bot-rs:{{ version }}
